### ISSUE TITLE
#13 is loading content from #18

### ISSUE THREAD

**Issue by alejandronanez** [tayiorbeii/egghead.io_redux_course_notes#30]
Open https://github.com/tayiorbeii/egghead.io_redux_course_notes/blob/master/13-React_Todo_List_Example_(Toggling_a_Todo).md and you'll see content from # 18

**Comment by tayiorbeii** [comment]
@alejandronanez The numbers of the files don't necessarily match the numbers of the videos-- for example, files 01 and 02 contain information for multiple video files. Sometimes it didn't make sense to have a very short writeup in its own file.

**Comment by tayiorbeii** [comment]
@alejandronanez Thanks for taking time to file an issue though! 😎

**Comment by alejandronanez** [comment]
@tayiorbeii np! Great repo BTW 😎
