### ISSUE TITLE
JSBin code

### ISSUE THREAD

**Issue by jhegedus42** [tayiorbeii/egghead.io_redux_course_notes#39]
Where can I find the JSBins that were used for this presentation ? Are they available ?

https://jsbin.com/

**Comment by jhegedus42** [comment]
something like this : https://jsbin.com/kaloqanise/1/edit?js,output

**Comment by jhegedus42** [comment]
code search does not really help : https://searchcode.com/?q=filterlink&loc=0&loc2=10000&lan=22

**Comment by jhegedus42** [comment]
found this : https://jsbin.com/jeqeyup/edit?js,console,output

**Comment by jhegedus42** [comment]
and this https://jsbin.com/xatafixuke/1/edit?html,js,output

**Comment by jhegedus42** [comment]
created a pr https://github.com/tayiorbeii/egghead.io_redux_course_notes/pull/40

**Comment by tayiorbeii** [comment]
https://twitter.com/dan_abramov/status/791973525498331141
